from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


def _load_node_link(path: Path) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    nodes = data.get("nodes") or []
    links = data.get("links") or data.get("edges") or []
    if not isinstance(nodes, list) or not isinstance(links, list):
        raise ValueError(f"Unexpected node-link JSON structure in {path}")
    return nodes, links


def export_csv(graph_json: Path, out_dir: Path) -> tuple[Path, Path]:
    nodes, links = _load_node_link(graph_json)
    out_dir.mkdir(parents=True, exist_ok=True)

    nodes_csv = out_dir / f"{graph_json.stem}.nodes.csv"
    edges_csv = out_dir / f"{graph_json.stem}.edges.csv"

    with nodes_csv.open("w", newline="", encoding="utf-8") as fp:
        writer = csv.DictWriter(fp, fieldnames=["id", "kind", "attrs_json"])
        writer.writeheader()
        for node in nodes:
            node_id = node.get("id") or node.get("name")
            if not node_id:
                continue
            kind = node.get("kind") or node.get("language") or ""
            attrs_json = json.dumps({k: v for k, v in node.items() if k not in {"id"}}, ensure_ascii=False)
            writer.writerow({"id": str(node_id), "kind": str(kind), "attrs_json": attrs_json})

    with edges_csv.open("w", newline="", encoding="utf-8") as fp:
        writer = csv.DictWriter(
            fp,
            fieldnames=["source", "target", "transformation_type", "source_file", "attrs_json"],
        )
        writer.writeheader()
        for link in links:
            source = link.get("source")
            target = link.get("target")
            if source is None or target is None:
                continue
            attrs_json = json.dumps(
                {k: v for k, v in link.items() if k not in {"source", "target"}},
                ensure_ascii=False,
            )
            writer.writerow(
                {
                    "source": str(source),
                    "target": str(target),
                    "transformation_type": str(link.get("transformation_type") or ""),
                    "source_file": str(link.get("source_file") or ""),
                    "attrs_json": attrs_json,
                }
            )

    return nodes_csv, edges_csv


def export_cypher(nodes_csv: Path, edges_csv: Path, out_dir: Path) -> Path:
    """
    Write a Cypher script that Memgraph Lab can execute.

    Assumes the CSVs are mounted into the Memgraph container at `/import`.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    cypher_path = out_dir / "import.cypher"

    nodes_url = f"file:///import/{nodes_csv.name}"
    edges_url = f"file:///import/{edges_csv.name}"

    cypher = f"""
// Auto-generated by scripts/export_memgraph.py

// Optional cleanup (uncomment if you want a fresh import)
// MATCH (n) DETACH DELETE n;

CREATE INDEX ON :Asset(id);

LOAD CSV FROM "{nodes_url}" WITH HEADER AS row
CREATE (:Asset {{
  id: row.id,
  kind: row.kind,
  attrs_json: row.attrs_json
}});

LOAD CSV FROM "{edges_url}" WITH HEADER AS row
MATCH (s:Asset {{id: row.source}}), (t:Asset {{id: row.target}})
CREATE (s)-[:DEPENDS_ON {{
  transformation_type: row.transformation_type,
  source_file: row.source_file,
  attrs_json: row.attrs_json
}}]->(t);
""".lstrip()

    cypher_path.write_text(cypher, encoding="utf-8")
    return cypher_path


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export .cartography graph JSON for Memgraph Lab.")
    parser.add_argument("--graph", required=True, help="Path to .cartography/*.json (node-link format).")
    parser.add_argument("--out-dir", default="build/memgraph", help="Output directory (default: build/memgraph).")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    graph_json = Path(args.graph)
    out_dir = Path(args.out_dir)

    nodes_csv, edges_csv = export_csv(graph_json, out_dir)
    cypher_path = export_cypher(nodes_csv, edges_csv, out_dir)

    print(f"Wrote: {nodes_csv}")
    print(f"Wrote: {edges_csv}")
    print(f"Wrote: {cypher_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

